biocommons/anyvar

README.md, src/anyvar/storage/__init__.py, src/anyvar/storage/pg_utility.py, src/anyvar/storage/postgres_init.sql
Changes the scheme from `postgres` to `postgresql` to follow the connection URIs as mentioned in the (docs)[https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING]
=> docs: update readme for postgres setup

.gitignore, src/anyvar/restapi/_data/openapi.yaml, src/anyvar/restapi/routes/summary_statistics.py, src/anyvar/storage/postgres.py
closes #13 
we don't know how to currently support deletion-insertion events and duplications. we just support general substitutions, insertions, and deletions.
=> feat #13: get statistics about variation content

src/anyvar/restapi/main.py
Simple fix for https://github.com/biocommons/anyvar/security/code-scanning/1. Logging the error should be fine.
=> fix: don't expose stack in error response

pyproject.toml
Updated `pyproject.toml` file to resolve issue with `make devready` build command.
=> Added 'dependencies' and 'optional-dependencies' to dynamic list

README.md, setup.cfg, src/anyvar/anyvar.py, src/anyvar/storage/postgres.py, src/anyvar/storage/snowflake.py, tests/conftest.py, tests/storage/test_snowflake.py, tests/storage/test_storage_mapping.py
Added an implementation of `anyvar.storage._Storage` that connects to a Snowflake database.
To facilitate processing whole genome VCF files without waits for database writes, the storage integration uses a background thread with queueing to write VRS object batches to the database.  There is one background thread created for each instance of the `SnowflakeObjectStore`, which in turn has one instance per HTTP worker.
Unit tests for the `MutableMapping` API (`tests/storage/test_storage_mapping.py`) and specific to the background thread behavior (`tests/storage/test_snowflake.py`) have been added.  The unit tests now cover the full storage API for both Postgres and Snowflake, though multiple runs with different `ANYVAR_TEST_STORAGE_URI` settings are required.  Bugs identified in the Postgres …
=> Snowflake database storage integration

setup.cfg, src/anyvar/extras/vcf.py, src/anyvar/restapi/main.py
Added a `for_ref` query parameter to the `/vcf` endpoint that determines whether VRS IDs are generated for REF alleles.  The default value is `True`, which is the current behavior.
The changes also include an adjustment to error handling in the `VcfRegistrar._get_vrs_object()` method.  The `VCFAnnotator` in vrs-python now includes exception handling that emits a `VRS_Error` INFO field if an error occurs computing VRS IDs for a VCF record.  So the `VcfRegistrar` no longer suppresses errors and logs them.  They are allowed to propagate up the stack.  And if no VRS object is generated by the translator, an exception is thrown.
See also #72
=> Add parameter to the /vcf endpoint to control whether VRS IDs are generated for REF alleles

src/anyvar/restapi/main.py, src/anyvar/storage/__init__.py, tests/conftest.py, tests/test_lifespan.py
The integration used by AnyVar to store, retrieve and query VRS objects should be provided an opportunity to complete pending work, shutdown and clean up when an AnyVar worker is shutdown.  The FastAPI provides lifespan events that can be used for this purpose.
The changes simply make the `close()` method part of the `_Storage` API definition and then call the method when the shutdown occurs.  Implementations of the `close()` already existed for both the PostgreSQL and Snowflake storage implementations.
The existing startup event handler was moved to a new lifespan method and the call to `close()` added to the lifespan method.  Event handlers have been deprecated in favor of [lifespan](https://fastapi.tiangolo.com/advanced/events/).
See also #66
=> Cleanup storage integration and write pending batches on shutdown

setup.cfg, src/anyvar/anyvar.py
In `AnyVar.put_object()`, use new parameter to `vrs_enref()` method to return both the object and identifier.  This eliminates the need to recompute the already computed digest and improve performance.
See also #71
=> Improve performance of AnyVar.put_object() by eliminating unnecessary digest computation

src/anyvar/restapi/main.py, src/anyvar/storage/__init__.py, src/anyvar/storage/postgres.py, src/anyvar/storage/snowflake.py, tests/storage/test_snowflake.py
The new Snowflake object store writes VRS objects to the database asynchronously to allow better response times.  However, since searches and fetches only read committed database state, this creates the opportunity for reads to not reflect the most recent VRS objects.
The current default behavior, and default behavior moving forward, is for all writes to complete before the response is returned to the client.  To enable writes to complete asynchronously after the response has been returned, clients can add the `allow_async_writes=yes` parameter to the request.
See also #65
=> Add parameter to /vcf endpoint to force async writes to complete before returning response

src/anyvar/extras/vcf.py, src/anyvar/restapi/main.py, src/anyvar/translate/translate.py, src/anyvar/translate/vrs_python.py, tests/storage/test_storage_mapping.py, tests/test_vcf.py
Allow caller of the `/vcf` endpoint to specify an `assembly` parameter that can be set to either `GRCh38` (default) or `GRCh37`.  The assembly is passed to through to the vrs-python `AlleleTranslator`.
Alternate assembly names (e.g. hg38) are not supported by this change.
Updated unit tests to include computing VRS IDs for both assemblies and parameter validation.
=> Add support for GRCh37 to /vcf endpoint

README.md, src/anyvar/storage/postgres_init.sql
If you follow the postgres instructions in our docs you will now get a connection issue, with the postgres server rejecting the connection for not having a password.
This PR fixes this issue by updating the postgres user to have a password, and including that password in the connection string.
And includes a typo fix for `README-pg.md`
Depends on #82
=> Fix postgres connection issue and typo in postgres readme 

setup.cfg, src/anyvar/extras/vcf.py
See #84 
The AnyVar VCF annotator that overrides `_get_vrs_object()` ignores the `require_validation` parameter when invoking the translator.  The translator uses the default value `True` and validates the reference sequence.  This is the current behavior of the AnyVar VCF annotator.
=> Update VCF annotator code to be compatible with superclass in vrs-python

README.md, src/anyvar/storage/snowflake.py, tests/storage/test_snowflake.py
Two updates for Snowflake storage integration.
When creating tables for VRS objects, explicitly set the collation to `utf8` to ensure that VRS ID comparisons are case-sensitive.
Support private key authentication for Snowflake connections.  This is done by adding the `private_key` parameter to the Snowflake connection URI.  The value is a file path or URL-encoded key material.  Examples:
```
...&private_key=path/to/private_key.p8
```
Or
```
...&private_key=-----BEGIN+PRIVATE+KEY-----%0AMIIEvAIBA...
```
If the private key material is encrypted, the `ANYVAR_SNOWFLAKE_STORE_PRIVATE_KEY_PASSPHRASE` environment variable must be set to the decryption password.
See also #88 and #89
=> Snowflake storage integration updates for collation and private key auth

src/anyvar/restapi/main.py, src/anyvar/restapi/schema.py, src/anyvar/storage/postgres.py, src/anyvar/storage/snowflake.py, tests/data/variations.json, tests/test_location.py, tests/test_variation.py, tests/test_vcf.py
Updated the unit tests inputs and expected outputs to match VRS 2.0.
In addition, the following changes were made:
- `__getitem__` now throws KeyError on missing key to match API expectations for `MutableMapping`
- Response models no longer reference `ga4gh.vrs.models` classes (see #91)
- `/locations/{id}` and `/variation/{id}` behave consistently and return 404 when `id` is not found
=> Update unit tests to match the new VRS 2.0 digests

pyproject.toml, src/anyvar/restapi/main.py, src/anyvar/storage/snowflake.py, tests/data/variations.json
The latest round of updates to the project configuration and dependency changes caused some things to break.
- Added sqlalchemy to list of required dependencies (#98)
- Disable FastAPI validation of response model for `/vcf` endpoint since the `FileResponse` is not valid pydantic field (#99)
- Fix handling of batch add mode setting in Snowflake connector (#100)
- Change variant test data to use "EFO:" instead of "efo:" in copy number objects because Pydantic deserialization was failing
=> Fix problems introduced by project configuration changes and dependency upgrades

src/anyvar/storage/sql_storage.py
Fix for #103 
Explicitly convert the `ANYVAR_SQL_STORE_FLUSH_ON_BATCHCTX_EXIT` environment variable from a string to a boolean.  Evaluates to `true` if the environment variable is `true`, `yes` or `1`, not case sensitive.
=> Convert ANYVAR_SQL_STORE_FLUSH_ON_BATCHCTX_EXIT  env value to boolean explicitly

README.md, src/anyvar/restapi/main.py, src/anyvar/storage/sql_storage.py
Implementation for #104 
When AnyVar starts up it will examine the value of the `ANYVAR_LOGGING_CONFIG` environment variable.  If the value points to a file, either absolute or relative path, AnyVar will attempt to load it, parse it as YAML and use the resulting data structure to configure the logging module using `dictConfig()`.
=> Add feature to allow logging configuration to be specified at runtime

README-async.md, README.md, pyproject.toml, src/anyvar/anyvar.py, src/anyvar/queueing/__init__.py, src/anyvar/queueing/celery_worker.py, src/anyvar/restapi/main.py, src/anyvar/restapi/schema.py, tests/conftest.py, tests/test_vcf.py
See also #107
The annotation of a large VCF file with VRS IDs can run for a long time.  A synchronous request-response pattern where the client is waiting for a response can lead to instability and dropped connections in many environments.  For long running processes, a better option is an asynchronous request-response pattern.  The client submits a request and receives a 202 response and polling location.  The client polls at some interval, receiving a 202 if the request is still pending, a 200 and the result if the request is completed, or a 500 if the request failed.
AnyVar uses the Celery distributed task queue for task management and result caching.  The asynchronous feature is optional and the changes for this PR are backwards compatible.
See the [README-async.md](README-async.md) …
=> VCF annotation via asynchronous request-response pattern

pyproject.toml
See https://github.com/biocommons/anyvar/discussions/111. Pinning `a12` for stability purposes in next release.
=> build: pin VRS-Python 2.0a12

src/anyvar/__init__.py
close https://github.com/biocommons/anyvar/issues/175
pulled directly from https://github.com/biocommons/biocommons.example/blob/main/src/biocommons/example/__init__.py
=> fix: don't use deprecated pkg_resources api for `__version__` value

pyproject.toml, src/anyvar/anyvar.py, src/anyvar/restapi/main.py
(ope) in https://github.com/biocommons/anyvar/pull/178 I added some more descriptive logging calls and also inserted a basic configuration call into the FastAPI app lifespan. I forgot that we already enabled use of a logging config to be loaded from a yaml file at `ANYVAR_LOGGING_CONFIG`. This PR moves the richer configuration stuff into the app lifespan code and gets rid of the redundant stuff. 
It does add an explicit `anyio` dependency, but that was already an implicit dependency via fastapi things.
=> fix: remove redundant logging
